### ISSUE TITLE
[BUG] - Device names seem to get overwritten

### ISSUE THREAD

**Issue by Rouzax** [ajarzyn/domoticz-luxtronic2#5]
I changed device names but they seem to get rewritten again with the default.
Not entirely sure when it happened

**Comment by ajarzyn** [comment]
Hello, thank you for this issue.

It's a design.
I've never found need to change the name of the device by hand thus I've always implemented it to update names together with other parameters of the device.

The problem is that if you choose to stop udating names functionallity of automatic translation would stop to work.

I could add additinal parameter to check if user want automatic or manual names, and update them acordingly.

**Comment by Rouzax** [comment]
Understand, in my case my wife also has access to Domoticz, so some names don't really mean anything to her, so I would like to be able to rename them to something meaning full in our house.

**Comment by ajarzyn** [comment]
I will take care of it together with #6
